### PR TITLE
Fix #16

### LINKED ISSUE #16: Footer text
Footer text overlaps buttons when window width is small.

.footer-message element occupies entire footer, covering up the buttons and preventing them from being clicked.

Text mostly just needs to be centered vertically, horizontal centering is nice but not as important.

### PR DESCRIPTION
**Pull request by JavascriptFTW**
This pull request fixes #16 and updates the footer slightly.

### Changes

* Move footer links below footer text.
* Add bottom border to footer text.
* Add borders between footer links.

I decided to put the footer text and links on separate lines as it was proving to be too much of a hassle to get everything to work on one line. Plus I think they look a bit better on separate lines.

### Screenshots

Screenshot of homepage

### CODE REVIEW

**Comment by jdsutton** [comment]
I don't know about having the links and text on separate lines. Would it be easier to manage on one line if the text were only centered vertically and not horizontally? Maybe we could, at least temporarily, fudge the centering with a little bit of a margin on the bottom.

**Comment by JavascriptFTW** [comment]
Yes, it would be easier if the text only needed to be centered vertically.

My problem was with getting the text centered horizontally and at the same time not have it overlap the links on small screen sizes. I'm sure there's some way to do this, but I couldn't figure one out.

I'm not certain what you mean about fudging it with a bottom margin. Could you please elaborate?

**Comment by jdsutton** [comment]
Well I just thought a simple cludge-y fix would be to add a few pixels of margin on the bottom to raise the text up to the center. 

Don't worry about centering the text horizontally. Send a new request with everything on one line and I'll merge it.

**Comment by JavascriptFTW** [comment]
Will do!

**Comment by JavascriptFTW** [comment]
How does this look?
onlineui3

**Comment by jdsutton** [comment]
Fantastic!

**Pull request closed without merging**
