### PR TITLE
Minor UI Tweak

### PR DESCRIPTION
**Pull request by JavascriptFTW**
This pull request tweaks the UI to be more appealing and modern (in my opinion) and also stops hard coding the client ID.

### Changes

* Tweaked the navbar and footer to be more appealing.
* Stopped hard coding the client ID for G+ logins.

If any changes are deemed necessary please let me know and I will get to them as soon as possible.

Thank you for your time.

### CODE REVIEW

**Comment by jdsutton** [comment]
There's a small problem with the style. The headers are getting covered up by the navbar: http://imgur.com/MvwFszM

Also I think the shade of green is a little bit strong. Other than that, the style looks good.

**Comment by JavascriptFTW** [comment]
I thought I had fixed that. I'll look into it tomorrow.

**Comment by jdsutton** [comment]
BTW another small tweak that would be really helpful is if you could get the text in the footer to be centered. It'd look much better.

**Comment by JavascriptFTW** [comment]
I got the footer text centered.

I also looked into the header problem and it renders perfectly on my local version (Windows 10 using Chrome 49.0.2623.75 m).

onlineui

What browser were you using when you got this behavior?

**Comment by jdsutton** [comment]
I'm using both Chrome and Firefox on Ubuntu. It's possible you forgot to commit you most recent changes and that's why they didn't show up. Please open a new pull request with your latest changes, thanks.

**Pull request closed without merging**
